[package]
authors = ["waylon531 <waylon531@firechicken.net>"]
edition = "2018"
name = "matrixlab"
version = "0.1.0"

[dependencies]
rayon = "1.0.3"
combine = "3.8"

[dev-dependencies]
proptest = "0.9.1"
